routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if(Auth::check()) return redirect('/home');
    return view('auth.login');
});

Auth::routes();

Route::middleware('auth')->group(function(){
    Route::get('/home', 'ContactController@index')->name('home');
    Route::resource('contact', 'ContactController', ['except' => [
        'index'
    ]]);
});

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    protected $fillable = [
        'name', 'surname', 'email',
        'phone', 'birth'
    ];

    public function getFullNameAttribute()
    {
        return "{$this->name} {$this->surname}";
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Contact;
use App\Http\Requests\ContactEditRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Lang;
use Validator;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contacts = Contact::paginate(10);
        return view('home', compact('contacts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('contact.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if($request->ajax()) {
            $validator = Validator::make($request->except(['_token', '_method']), [
                'name' => 'required|min:1',
                'surname' => 'required|min:1',
                'email' => 'email|unique:contacts,email',
                'phone' => 'required|min:6',
                'birth' => 'required',
            ]);

            if ($validator->fails()) {
                return response()->json(Lang::get($validator->errors()->first()));
            }
            Contact::create($request->except(['_token', '_method']));

            return response()->json(['success' => true], 200);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $contact = Contact::find($id);
        if(is_null($contact)) return redirect('/home');
        return view('contact.show', compact('contact'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $contact = Contact::find($id);
        return view('contact.edit', compact('contact'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if($request->ajax()) {
            $validator = Validator::make($request->except(['_token', '_method']), [
                'email' => 'email|unique:contacts,email,' . $id,
            ]);

            if ($validator->fails()) {
                return response()->json(Lang::get($validator->errors()->first()));
            }

            $contact = Contact::find($id);
            $result = $contact->update($request->except(['_token', '_method']));
            if ($result) {
                return response()->json(['success' => true], 200);
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $contact = Contact::find($id);

        if($contact->destroy($id)) {
            return response()->json(['success' => true], 200);
        }
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/contact/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Create new contact</div>
                    <div class="col-md-12 text-center">
                        <div class="alert alert-success" style="display: none;">
                            Successfully added
                        </div>
                        <div class="alert alert-danger" style="display: none;">

                        </div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('contact.store') }}" method="POST" id="c-form" onsubmit="return false;">
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="name">Name:</label>
                                    <input type="text" name="name" required class="form-control">
                                </div>
                                <div class="col-md-4">
                                    <label for="name">Surname:</label>
                                    <input type="text" name="surname" required class="form-control" >
                                </div>
                                <div class="col-md-4">
                                    <label for="name">E-mail:</label>
                                    <input type="text" name="email" required class="form-control email" >
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="name">Phone:</label>
                                    <input type="text" name="phone" required class="form-control" >
                                </div>
                                <div class="col-md-4">
                                    <label for="name">Birth:</label>
                                    <input type="date" name="birth" class="form-control" >
                                </div>
                            </div>
                            <hr/>
                            <div class="row">
                                <div class="col-md-12 text-right">
                                    <button type="submit" class="btn btn-success c-save">Create</button>
                                </div>
                            </div>
                            @method('POST')
                            @csrf
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@section('script')
    <script>
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $(".c-save").on('click', function(e){
            e.preventDefault();
            var form = $('#c-form');

            $.ajax({
                type:'POST',
                url:'{!! route("contact.store") !!}',
                data: form.serialize(),
                success:function(data){
                    if(data.success == true) {
                        $('.alert.alert-danger').fadeOut();
                        $('.alert.alert-success').fadeIn(400)
                            .delay(2000)
                            .fadeOut(600);
                    } else {
                        $('.alert.alert-danger').text(data);
                        $('.alert.alert-danger').fadeIn(400);
                    }
                }
            });
        });
    </script>
@endsection
@endsection

resources/views/contact/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Edit contact</div>
                   <div class="col-md-12 text-center">
                        <div class="alert alert-success" style="display: none;">
                            Successfully updated
                        </div>
                        <div class="alert alert-danger" style="display: none;">

                        </div>
                   </div>
                    <div class="card-body">
                        <form action="{{ route('contact.update', $contact->id) }}" method="POST" id="c-form" onsubmit="return false;">
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="name">Name:</label>
                                    <input type="text" name="name" required class="form-control" value="{{ $contact->name or ''}}">
                                </div>
                                <div class="col-md-4">
                                    <label for="name">Surname:</label>
                                    <input type="text" name="surname" required class="form-control" value="{{ $contact->surname or ''}}">
                                </div>
                                <div class="col-md-4">
                                    <label for="name">E-mail:</label>
                                    <input type="text" name="email" required class="form-control email" value="{{ $contact->email or ''}}">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="name">Phone:</label>
                                    <input type="text" name="phone" required class="form-control" value="{{ $contact->phone or ''}}">
                                </div>
                                <div class="col-md-4">
                                    <label for="name">Birth:</label>
                                    <input type="date" name="birth" class="form-control" value="{{ $contact->birth or ''}}">
                                </div>
                            </div>
                            <hr/>
                            <div class="row">
                                <div class="col-md-12 text-right">
                                    <button type="submit" class="btn btn-success c-save">Save</button>
                                </div>
                            </div>
                            @method('PATCH')
                            @csrf
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @section('script')
        <script>
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $(".c-save").on('click', function(e){
                e.preventDefault();
                var form = $('#c-form');

                $.ajax({
                    type:'POST',
                    url:'{!! route("contact.update", $contact->id) !!}',
                    data: form.serialize(),
                    success:function(data){
                        if(data.success == true) {
                            $('.alert.alert-danger').fadeOut();
                            $('.form-control.email').removeClass('is-invalid');
                            $('.alert.alert-success').fadeIn(400)
                                .delay(2000)
                                .fadeOut(600);
                        } else {
                            $('.alert.alert-danger').text(data);
                            $('.alert.alert-danger').fadeIn(400);
                            $('.form-control.email').addClass('is-invalid');
                        }
                    }
                });
            });
        </script>
    @endsection
@endsection

resources/views/contact/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Contact information</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif
                        <div class="row">
                            <div class="col-md-4">
                                <label for="name">Name:</label>
                                {{ $contact->name }}
                            </div>
                            <div class="col-md-4">
                                <label for="name">Surname:</label>
                                {{ $contact->surname }}
                            </div>
                            <div class="col-md-4">
                                <label for="name">E-mail:</label>
                                {{ $contact->email }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <label for="name">Phone:</label>
                                {{ $contact->phone }}
                            </div>
                            <div class="col-md-4">
                                <label for="name">Birth:</label>
                                {{ $contact->birth }}
                            </div>
                        </div>
                        <hr/>
                        <div class="row">
                            <div class="col-md-1 text-left">
                                <a href="{{ route('contact.edit', $contact->id) }}"><button class="btn btn-success">Edit</button></a>
                            </div><div class="col-md-2 text-left">
                                <a href="{{ route('contact.destroy', $contact->id) }}"><button class="btn btn-danger delete">Delete</button></a>
                            </div>
                            <div class="col-md-9 text-right">
                                <button class="btn btn-primary" onclick="window.history.back()">Back</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @section('script')
        <script>
            $('.btn.btn-danger.delete').on('click', function(e){
                e.preventDefault();
                    swal({
                    title: "Are you sure?",
                    text: "Once deleted, you will not be able to recover this!",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                })
                    .then((willDelete) => {
                    if (willDelete) {
                        swal("Poof! Contact has been deleted!", {
                            icon: "success",
                        });
                        var _token = $('meta[name="csrf-token"]').attr('content');
                        $.ajax({
                            type: 'POST',
                            method: 'DELETE',
                            data: {_token:_token},
                            url: '{!! route("contact.destroy", $contact->id) !!}',
                            success: function (data) {

                            }
                        });
                    }
                });
            });
        </script>
    @endsection
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">List of contacts
                    <a href="{{ route('contact.create') }}">
                        <button class="btn btn-success">Create new contact</button>
                    </a></div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                        <div class="list-group">
                            <div class="row">
                                <div class="col-md-12">
                                @forelse($contacts as $contact)
                                        <a href="{{ route('contact.show', $contact->id) }}" class="list-group-item list-group-item-action">
                                            {{ $contact->full_name }}
                                        </a>
                                @empty
                                    Empty list
                                @endforelse
                                </div>
                            </div>
                        </div>
                </div>
            </div>
            <br/>
            {{ $contacts->render() }}
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @yield('script')
</body>
</html>